[package]
name = "monnos"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]
path = "kernel/kernel.rs"

[profile.dev]
opt-level = "z"
strip = true
lto = true

[dependencies]
no-panic = "0.1.29"
